### ISSUE TITLE
npm run e2e fails

### ISSUE THREAD

**Issue by beaverusiv** [angular/quickstart#250]
e2e fails because webdriver-manager is installing chromedriver 2.22 instead of 2.24. webdriver-manager@10.2.3 has the right chromedriver but protractor depends on @10.2.2 instead.

Is there a way to fix this? Currently I can get it working by downloading 2.24 and renaming it to 2.22.

**Comment by sthibert** [comment]
Another workaround: Modify the file `node_modules/protractor/config.json` by changing `"chromedriver": "2.21"` to `"chromedriver": "2.24"` (see https://github.com/angular/webdriver-manager/issues/102).

**Comment by emilong** [comment]
You can also work around this by using the command line arg `--versions.chrome 2.24` for all commands (update and start).

**Comment by cnishina** [comment]
webdriver-manager@10.2.4 has been released and it should download chromedriver 2.24 by default.

**Comment by filipesilva** [comment]
@cnishina thanks for the update. Clean installs should now work.

**Comment by isaac2004** [comment]
I did a fresh install of this today and am still getting this issue. Latest of this repo and node.
